version: '3.8'

services:
  backend:
    build: .
    container_name: user_management_service
    ports:
      - "5000:5000"   # host:container
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
